/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jojopojo' at '10/30/15 11:49 AM' with Gradle 2.8
 *
 * @author jojopojo, @date 10/30/15 11:49 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
